### ISSUE TITLE
Doesn't appear to generate any text

### ISSUE THREAD

**Issue by lsd87** [CullenJWebb/Cullenect-Labels#1]
Can't see any text generation on the label, even after F6
SCAD V2024.09.30

![image](https://github.com/user-attachments/assets/251aaf9c-768c-4f81-b4aa-26df65b7fcfd)

**Comment by CullenJWebb** [comment]
Sorry about that, I mixed up the branches. You can download it again and you should have a working version.

**Comment by lsd87** [comment]
Thanks - lot better
Changing the font family does not appear to do anything is this due to running on windows 10 ?
Also would be nice to select how high the text sits from the surface, sometimes the text kinds of merges into the background

Looking forward to chris (osat) installing the vertical click rails in his bin generator 

Thanks

**Comment by CullenJWebb** [comment]
@lsd87 That may be because you don't have the fonts installed.

I've added it to the makerworld listing here if you want to try out the fonts there without installing: https://makerworld.com/models/446624

I'm very excited to see Chris integrate the socket in his bins. I may make my own solution in the meantime to replace the V1 bins on makerworld ASAP.

**Comment by lsd87** [comment]
Installed fonts and now works fine.

Will also be great when gflabel @ndevenish supports your click V2 ?

**Comment by CullenJWebb** [comment]
@lsd87 I believe so, I've kept them up to date with the progress on V2 and they expressed interest in keeping gflabel up to date.

**Comment by ndevenish** [comment]
I plan to, but was only told about the v2 release two days ago! I plan to have a look this weekend to see how close to the prototype v2 the final release is, and update.

**Comment by CullenJWebb** [comment]
@ndevenish Thank you thank you!
