### ISSUE TITLE
design feedback

### ISSUE THREAD

**Issue by ostat** [CullenJWebb/Cullenect-Labels#3]
@CullenJWebb, great work on the new design of the labels.

If you don't mind, could we provide feedback on the design?

If we can it would be nice to not need to use supports when printing. I assume most people will print this text side up. Is there an opportunity to add a chamfer to the underside of the upper lip? 
In version 1 this did not add much value as the ribs in the middle were still not supported, in version 2 I think this adds value.

This is just a draft, to explain what I mean.
![image](https://github.com/user-attachments/assets/fb7d5360-db38-4a52-baee-0f80e84789d7)

Aesthetically, I would make the radius if the inner setback different from the outer, so that there is a consistent overhang.
Currently
![image](https://github.com/user-attachments/assets/19cfee94-62e6-4d88-a86b-ff77c0058f35)
Suggested
![image](https://github.com/user-attachments/assets/db5f2df3-d290-4266-a685-90d3c2a4ecd6)

I can submit PR's if you are interested

**Comment by CullenJWebb** [comment]
I will check on the radius.

The chamfer from V1 isn't needed though, I think. The overhang is so small that it holds form really well and keeps the geometry simpler.

Same for the socket rails, they don't have chamfers but their width was less than the nozzle extrusion width on a 0.4mm.

What printers do you have? I don't have any old ones around to test with and I do want to make sure that enders and other bedslingers can print them so I'll test the chamfer just in case we need them.

**Comment by ostat** [comment]
> The chamfer from V1 isn't needed though, I think. The overhang is so small that it holds form really well and keeps the geometry simpler.
> 
> Same for the socket rails, they don't have chamfers but their width was less than the nozzle extrusion width on a 0.4mm.
> 
> What printers do you have? I don't have any old ones around to test with and I do want to make sure that enders and other bedslingers can print them so I'll test the chamfer just in case we need them.

oh right, I didn't really consider the scale of the model when looking at it

**Comment by CullenJWebb** [comment]
> oh right, I didn't really consider the scale of the model when looking at it

This tripped me up so much during the design of both V1 and V2. Being able to zoom in and rotate around causes me to lose all sense of relative size. 

This was why V1 had such bad vertical sockets, I didn't appreciate the fact that printers wouldn't be able to print the 3 latches when they were turned on their side. V2 still requires some creative movements to be modeled into the 2 side rails so that it can be printed in a single motion without any seams.
