### ISSUE TITLE
Error - Can't open Cullenect.json

### ISSUE THREAD

**Issue by lsd87** [CullenJWebb/Cullenect-Labels#7]
Using OpenSCAD 2024.11.03 

I get this error when opening the scad file

ERROR: Cannot open Parameter Set 'D:/Temp/Cullenect-Labels-main/OpenSCAD/Cullenect.json': D:/Temp/Cullenect-Labels-main/OpenSCAD/Cullenect.json(52): expected key string

But its there
![image](https://github.com/user-attachments/assets/ed25db8b-29c8-4520-b737-7b4e80f696e5)

**Comment by CullenJWebb** [comment]
It looks like it is able to find the file but it encounters an error with one of the parameters. It's expecting a string but it gets something else.

Try renaming the file as a test and see if it loads for you then.

**Comment by CullenJWebb** [comment]
Looks like I goofed up the json file. Go ahead and delete that, it's not needed. I've removed it from the repo and I'll make sure it's clean in a future update.

**Comment by lsd87** [comment]
Delete the json file and now get

Loaded design 'D:/Temp/Cullenect-Labels-main/OpenSCAD/Cullenect.scad'.
[ERROR: Parser error: syntax error in file Cullenect.scad, line 1](https://github.com/CullenJWebb/Cullenect-Labels/issues/1,D:/Temp/Cullenect-Labels-main/OpenSCAD/Cullenect.scad)
Execution aborted

**Comment by CullenJWebb** [comment]
Looks like whatever I did to bork the JSON also borked the .scad file. I've fixed it and updated the repo, sorry about the trouble.

If you download it anew it should work.
